g++ -c main.cpp src/character.cpp -I /home/tranxen/Documents/Project/SFML-2.0-rc/include/
g++ main.o character.o -o ./testAI -L /home/tranxen/Documents/Project/SFML-2.0-rc/lib -lsfml-graphics -lsfml-window -lsfml-system
